- name: My first play
  hosts: web_servers
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world, I am pinging my vm web servers using an ansible playbook. 

